# Generated by Django 4.0.4 on 2022-07-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_groups_main_course'),
        ('students', '0003_alter_students_options_alter_students_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.groups'),
        ),
    ]
