# Generated by Django 4.0.4 on 2022-05-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
    ]
