# Generated by Django 4.0.4 on 2022-05-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teachers_phone_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachers',
            table='teachers',
        ),
    ]
