# Generated by Django 4.0.4 on 2022-06-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groups_options_alter_groups_table'),
        ('teachers', '0004_alter_teachers_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='groups.groups'),
        ),
    ]
