# Generated by Django 4.0.4 on 2022-06-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_main_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='main_group',
        ),
    ]
