# Generated by Django 4.0.4 on 2022-05-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
    ]
