# Generated by Django 4.0.4 on 2022-05-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groups',
            table='teachers',
        ),
    ]
