# Generated by Django 4.0.4 on 2022-05-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groups_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.AlterModelTable(
            name='groups',
            table='groups',
        ),
    ]
