# Generated by Django 4.0.4 on 2022-06-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('groups', '0004_alter_groups_options_alter_groups_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'groups', 'verbose_name_plural': 'groups'},
        ),
        migrations.AddField(
            model_name='groups',
            name='main_course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_course', to='courses.courses'),
        ),
    ]
