# Generated by Django 4.0.4 on 2022-06-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groups_options_groups_main_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
        migrations.RemoveField(
            model_name='groups',
            name='main_course',
        ),
    ]
