# Generated by Django 4.0.4 on 2022-07-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courses_main_group'),
        ('groups', '0007_alter_groups_options_groups_main_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='main_course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_courses', to='courses.courses'),
        ),
    ]
